on:
  push:
    tags:
      - 'v*' 

name: release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 16
        uses: actions/setup-node@v2.2.0
        with:
          node-version: 16.x

      - run: npm ci

      - name: Set env
        run: | 
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          echo "RELEASE_NAME=${{ github.event.repository.name }}-${{ env.RELEASE_VERSION}}" >> $GITHUB_ENV

      - name: Create changelog
        run: |
          ./.get_latest_changes_for_release_notes.sh > ./${RELEASE_NAME}.md

      - name: Create release binaries
        run: |
          set -x
          npx pkg --compress GZip --targets node16-linux-x64,node16-alpine-x64,node16-linuxstatic-x64 lib/index.js
          mv index-alpine "${{ env.RELEASE_NAME }}"-alpine-x64
          mv index-linux "${{ env.RELEASE_NAME }}"-linux-x64
          mv index-linuxstatic "${{ env.RELEASE_NAME }}"-linuxstatic-x64
          ls -l

      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            ${RELEASE_NAME}-alpine-x64
            ${RELEASE_NAME}-linux-x64
            ${RELEASE_NAME}-linuxstatic-x64
          tag_name: ${{ github.ref }}
          name: ${{ env.RELEASE_VERSION }}
          body_path: ./${{ env.RELEASE_NAME }}.md