name: tests

on: push

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [11.x, 12.x, 13.x, 14.x]

    steps:
    - name: Git checkout
      uses: actions/checkout@master

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2.2.0
      with:
        node-version: ${{ matrix.node-version }}

    - run: npm ci

    - run: npm test
      env:
        NODE_ENV: ci

    - run: |
        export RELEASE_NAME=prometheus-what-active-users-exporter-snapshot
        npx pkg --compress GZip --targets node16-linux-x64,node16-alpine-x64,node16-linuxstatic-x64 lib/index.js
        mv index-alpine ${RELEASE_NAME}-alpine-x64
        mv index-linux ${RELEASE_NAME}-linux-x64
        mv index-linuxstatic ${RELEASE_NAME}-linuxstatic-x64
        ls -l